### ISSUE TITLE
Good peers getting banned after chunks are removed from storage

### ISSUE THREAD

**Issue by ccampbell** [anacrolix/torrent#364]
I have been testing this library using an in-memory lru cache with a small readahead time. One of the issues I have observed is that when chunks get evicted from the cache and the piece completion state changes, if I then seek back to try to re-download those chunks, in a lot of cases the peers end up getting banned, and the download seems to hang for a long time. I see a bunch of messages like this in the logs:

```
2020-01-06 00:50:54 client.go:1222: banning ip 5.39.78.105
2020-01-06 00:51:07 client.go:1222: banning ip 5.39.78.105
2020-01-06 00:51:10 client.go:1222: banning ip 5.39.78.105
2020-01-06 00:51:12 client.go:1222: banning ip 5.39.78.105
2020-01-06 00:51:18 client.go:1222: banning ip 5.39.78.105
2020-01-06 00:51:19 client.go:1222: banning ip 5.39.78.105
2020-01-06 00:51:20 client.go:1222: banning ip 5.39.78.105
2020-01-06 00:51:21 client.go:1222: banning ip 5.39.78.105
2020-01-06 00:51:22 client.go:1222: banning ip 5.39.78.105
2020-01-06 00:51:24 client.go:1222: banning ip 5.39.78.105
2020-01-06 00:51:26 client.go:1222: banning ip 99.242.55.224
2020-01-06 00:51:28 client.go:1222: banning ip 185.149.90.102
2020-01-06 00:51:48 client.go:1222: banning ip 195.154.176.126
2020-01-06 00:52:25 client.go:1222: banning ip 84.94.62.90
2020-01-06 00:52:27 client.go:1222: banning ip 185.149.90.32
2020-01-06 00:53:47 client.go:1222: banning ip 2.44.118.238
2020-01-06 00:54:09 client.go:1222: banning ip 216.244.83.187
2020-01-06 00:54:41 client.go:1222: banning ip 195.154.225.54
```

I mentioned this to you over email and your reply you said:

> My theory is that chunks arriving after piece is marked for hashing are added to the dirty list (after it's already cleared in preparation to be hashed). Later when the pieces are evicted from the cache, a piece check fails and those peers that sent late, overlapping chunks are being banned (despite being innocent). If your cache was small enough, and chunks were redundant, and hashes took a while, this would occur quite a lot. I think the solution is to disallow writing chunks while piece checks are pending or active.

**Comment by anacrolix** [comment]
My tests for the above theory haven't shown anything up. I think now that it's more likely that incomplete pieces are being evicted, and the Client blames the dirtiers for the piece hash failures.

**Comment by ccampbell** [comment]
That sounds possible/likely. Do you think it should be handled outside of the library? Or perhaps there is something I can add in my fork to fix it…

https://github.com/anacrolix/torrent/blob/c23eca4812aa74184b92444fd3978de8f2ab7052/torrent.go#L1705-L1713

**Comment by anacrolix** [comment]
I think it should be handled inside the library. Data moving away, and disk problems would fall into the same category.

**Comment by anacrolix** [comment]
After a lot of testing, I think the best solution is to have incomplete piece storage handle chunks explicitly.

**Comment by anacrolix** [comment]
Could you try with branch [`issue-364`](https://github.com/anacrolix/torrent/tree/issue-364). In the branch, the resource per piece storage type is modified to store incomplete chunks separately, so that if they're evicted an error is returned while hashing. It's not currently used, but I think it will be a viable strategy to determine whether to ban peers for a failure.

**Comment by ccampbell** [comment]
Thanks. Will try later today.

**Comment by ccampbell** [comment]
Okay, I tested a bit with a 50MB cache size seeking around on a 2 GB file and the peers getting banned seems to be resolved (assuming they are still being logged).

It still gets stuck and hangs a bit though when seeking back to previously downloaded parts. That may just be normal behavior, but I am not sure because it does _not_ seem to happen if I start fresh and seek ahead to pieces that have never been downloaded before.

It definitely seems to be better than before though because before sometimes it could get stuck for minutes or not resume at all.

I see a bunch of these in the logs now too:

```
2020-01-09 20:52:57 torrent.go:1673: "Torrent Name": piece {InfoHash}/292 (68839804f421cb596bf90ef994419158b2b9bbd6) hash failure copy error: unexpected EOF
2020-01-09 20:52:58 torrent.go:1673: "Torrent Name": piece {InfoHash}/293 (6bcdd8729b93ccacc3c1f0c649c1c13d7aa8aacc) hash failure copy error: unexpected EOF
2020-01-09 20:52:59 torrent.go:1673: "Torrent Name": piece {InfoHash}/294 (02241fde079c6cb3119e29d0eef35cc7cf440395) hash failure copy error: unexpected EOF
2020-01-09 20:53:00 torrent.go:1673: "Torrent Name": piece {InfoHash}/295 (45f057bdde72ba2d4168a2c674baaebab1c4c6e5) hash failure copy error: unexpected EOF
2020-01-09 20:53:02 torrent.go:1673: "Torrent Name": piece {InfoHash}/296 (729a21404a5d90b7936b7edaf56129ecb5383a6e) hash failure copy error: unexpected EOF
```

**Comment by anacrolix** [comment]
This should now be fixed by https://github.com/anacrolix/torrent/commit/cf0d0118ea99e8492cf997e6d82b4105da4a3c76. If a storage backend returns an appropriate error when reading incomplete data to hash a piece, no peer should be banned.

**Comment by ccampbell** [comment]
Hey thanks. I am now trying with the latest master, but I am noticing the behavior seems to be worse now. I don’t think peers are being banned (at least I don’t see anything in the logs), but something is causing downloads to hang, and it is getting stuck even when making normal requests (without seeking back). Also still seeing a lot of these in the logs

```
2020-01-23 16:15:08 torrent.go:1698: "Torrent Name": piece {InfoHash}/559 (f192938f1236ee609fb349c0b450711af7af448a) hash failure copy error: unexpected EOF
2020-01-23 16:15:08 torrent.go:1698: "Torrent Name": piece {InfoHash}/561 (c19f09ae322fcfcd64b526695d76822ddb631556) hash failure copy error: unexpected EOF
2020-01-23 16:15:08 torrent.go:1698: "Torrent Name": piece {InfoHash}/560 (d3b81e53fee096978303019104bdaa5075d2445a) hash failure copy error: unexpected EOF
2020-01-23 16:15:08 torrent.go:1698: "Torrent Name": piece {InfoHash}/563 (7223a32ccb4d2abe985b366e746a7534486a264c) hash failure copy error: unexpected EOF
2020-01-23 16:15:08 torrent.go:1698: "Torrent Name": piece {InfoHash}/562 (17595085ad5806077c29d2f15b65f16dd9b2a1f0) hash failure copy error: unexpected EOF
2020-01-23 16:15:08 torrent.go:1698: "Torrent Name": piece {InfoHash}/564 (d975d09812de093cd42206bc7a24b75fc61baaa7) hash failure copy error: unexpected EOF
```

Is there something special I have to do in my LRU storage? Or any logs that would be helpful to debug it?

**Comment by anacrolix** [comment]
@ccampbell can you share the LRU cache code? The main change is that you must ensure that cache evictions result in errors when reading from the storage pieces. But it should still work even if you don't: that's the case where it might ban peers despite the reason for hash failure being a storage issue. However, it might be that the implementation used by a given storage wrapper returns errors even on successful reads (such as io.EOF and the end of a file), and passes those through. Again, that shouldn't actually cause your downloads to stall completely unless all the useful peers were banned.

**Comment by anacrolix** [comment]
https://github.com/anacrolix/torrent/commit/913f6df80d4eac2c18980e4b0f10d746427e2ecf and https://github.com/anacrolix/torrent/commit/72e54fb353128ef85f00ec7c2c94b8648f1eb889 are particularly relevant.

**Comment by ccampbell** [comment]
First I want to test a bit with the regular storage backends and confirm that the issues are specific to my LRU storage cause I am noticing it hanging even with a fresh cache without any evictions yet which seems weird. It definitely didn’t do that before. If it is specific to my code then I will try to find a way to share it. It is scattered through a few private repos now and not in its own package.

**Comment by ccampbell** [comment]
I am noticing the same behavior using the bolt db storage. Could it actually have something to do with the requestStrategy changes in #366 ? Basically what I am seeing is, if a video is playing, it will play a few seconds then stop then play a few more seconds. I haven’t added any logging to see what specifically is happening, but this is definitely something new after updating to the latest master.

I am also using a readahead of 1MB in my reader

```go
reader := t.NewReader()
reader.SetReadahead(1 * 1024 * 1024)
```

I can try playing with the readahead and requestStrategy values to see if it makes any difference

**Comment by anacrolix** [comment]
Yes it could be the request strategy changes. It might be putting too many requests onto a single slow connection. This is why I didn't set the new request strategy to be the default previously. The old strategy was `requestStrategyTwo`. I'm not seeing the speed issue with my instances that are using caching though (could be better peers or something?).

**Comment by ccampbell** [comment]
Is there any public access to the default request strategies to set them externally via the config or do they have to be created manually?

**Comment by anacrolix** [comment]
@ccampbell they have to be set in the code for now, I haven't exposed them sorry.

**Comment by ccampbell** [comment]
Is there an easy way to change it back to the old request strategy? I tried adding this 

```
func requestStrategyTwoMaker(duplicateRequestTimeout time.Duration) requestStrategyMaker {
	return func(callbacks requestStrategyCallbacks, clientLocker sync.Locker) requestStrategy {
		return requestStrategyTwo{}
	}
}
```

But now it seems to crash every time (seems maybe the old request strategy is not fully implemented?):

I basically just want to isolate that the issues I am noticing are related to the request strategy change and not the bad piece changes.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x44c8597]

goroutine 1301 [running]:
github.com/anacrolix/torrent.(*connection).request(0xc00053e600, 0x7800000000223, 0xc000004000, 0xc0008018b0, 0xc000834000)
	/Users/craig/Sites/torrent/connection.go:536 +0x317
github.com/anacrolix/torrent.(*connection).fillWriteBuffer.func1.1(0x7800000000223, 0x66f3fd1e00004000, 0x0)
	/Users/craig/Sites/torrent/connection.go:591 +0x13c
github.com/anacrolix/torrent.(*connection).iterPendingRequests.func1(0x400000078000, 0x66f3fd1e0000001e)
	/Users/craig/Sites/torrent/connection.go:810 +0x3d
github.com/anacrolix/torrent.defaultIterUndirtiedChunks.func1(0x1e, 0x80)
	/Users/craig/Sites/torrent/connection.go:839 +0x93
github.com/anacrolix/missinggo/iter.ForPerm(0x80, 0xc0009bb8b8, 0x80)
	/Users/craig/go/pkg/mod/github.com/anacrolix/missinggo@v1.2.1/iter/iterutils.go:36 +0xbd
github.com/anacrolix/torrent.defaultIterUndirtiedChunks(0x48ba4c0, 0xc0007b75e0, 0xc000457560, 0xc000457560)
	/Users/craig/Sites/torrent/connection.go:834 +0xea
github.com/anacrolix/torrent.requestStrategyTwo.iterUndirtiedChunks(...)
	/Users/craig/Sites/torrent/connection.go:848
github.com/anacrolix/torrent.(*connection).iterPendingRequests(0xc00053e600, 0x223, 0xc000457540, 0xc000577020)
	/Users/craig/Sites/torrent/connection.go:807 +0xcc
github.com/anacrolix/torrent.(*connection).fillWriteBuffer.func1(0x223, 0x46e3b00)
	/Users/craig/Sites/torrent/connection.go:573 +0x97
github.com/anacrolix/torrent.defaultIterPendingPieces.func1(0x223, 0xc0005dfa01)
	/Users/craig/Sites/torrent/connection.go:791 +0x2f
github.com/anacrolix/missinggo/v2/prioritybitmap.(*PriorityBitmap).IterTyped.func1(0x223, 0x46e3b00)
	/Users/craig/go/pkg/mod/github.com/anacrolix/missinggo/v2@v2.3.2-0.20200110051601-fc3212fb3984/prioritybitmap/prioritybitmap.go:143 +0x2f
github.com/anacrolix/missinggo/v2/prioritybitmap.(*PriorityBitmap).IterTyped.func2(0x46e3b00, 0xc0005647d0, 0x8)
	/Users/craig/go/pkg/mod/github.com/anacrolix/missinggo/v2@v2.3.2-0.20200110051601-fc3212fb3984/prioritybitmap/prioritybitmap.go:149 +0x162
github.com/anacrolix/missinggo/iter.All.func1(0x46e3b00, 0xc0005647d0, 0x203000)
	/Users/craig/go/pkg/mod/github.com/anacrolix/missinggo@v1.2.1/iter/func.go:14 +0x5c
github.com/anacrolix/missinggo/orderedmap.(*GoogleBTree).Iter.func1(0x48adce0, 0xc000591ce0, 0x203000)
	/Users/craig/go/pkg/mod/github.com/anacrolix/missinggo@v1.2.1/orderedmap/google_btree.go:89 +0x4d
github.com/google/btree.(*node).iterate(0xc00080b880, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc000450000, 0xc0009bbb98, 0xc0005dfc30)
	/Users/craig/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:524 +0x549
github.com/google/btree.(*BTree).Ascend(...)
	/Users/craig/go/pkg/mod/github.com/google/btree@v1.0.0/btree.go:777
github.com/anacrolix/missinggo/orderedmap.(*GoogleBTree).Iter(0xc000801120, 0xc0004574c0)
	/Users/craig/go/pkg/mod/github.com/anacrolix/missinggo@v1.2.1/orderedmap/google_btree.go:88 +0x83
github.com/anacrolix/missinggo/iter.All(0xc0004574a0, 0xc0009bbc38, 0x1, 0x1, 0xc0005dfc60)
	/Users/craig/go/pkg/mod/github.com/anacrolix/missinggo@v1.2.1/iter/func.go:13 +0xb4
github.com/anacrolix/missinggo/v2/prioritybitmap.(*PriorityBitmap).IterTyped(0xc00053e880, 0xc0008018c0, 0xc00053e600)
	/Users/craig/go/pkg/mod/github.com/anacrolix/missinggo/v2@v2.3.2-0.20200110051601-fc3212fb3984/prioritybitmap/prioritybitmap.go:145 +0x120
github.com/anacrolix/torrent.defaultIterPendingPieces(0x48bf5e0, 0x4cfa5c8, 0x48c10e0, 0xc00053e600, 0xc000457480, 0xc000457480)
	/Users/craig/Sites/torrent/connection.go:790 +0xb6
github.com/anacrolix/torrent.requestStrategyTwo.iterPendingPieces(...)
	/Users/craig/Sites/torrent/connection.go:799
github.com/anacrolix/torrent.(*connection).iterPendingPieces(...)
	/Users/craig/Sites/torrent/connection.go:781
github.com/anacrolix/torrent.(*connection).fillWriteBuffer(0xc00053e600, 0xc0008018b0)
	/Users/craig/Sites/torrent/connection.go:572 +0x2cb
github.com/anacrolix/torrent.(*connection).writer(0xc00053e600, 0xdf8475800)
	/Users/craig/Sites/torrent/connection.go:634 +0x618
created by github.com/anacrolix/torrent.(*Client).runHandshookConn
	/Users/craig/Sites/torrent/client.go:884 +0x52d
```

**Comment by ccampbell** [comment]
I also tried changing the `duplicateRequestTimeout` for `requestStrategyThree`, but it still seems to hang.

**Comment by anacrolix** [comment]
I've [exposed](https://godoc.org/github.com/anacrolix/torrent#RequestStrategyMaker) the builtin request strategies, and their panics should be fixed.

**Comment by ccampbell** [comment]
Thanks! Will try it out later today

**Comment by ccampbell** [comment]
Okay. Using `torrent.RequestStrategyFastest()` works! So that was the issue. I haven’t tested extensively, but everything seems to work fine now.

Using the new default (`RequestStrategyDuplicateRequestTimeout`) does not seem to work very well for me at all though. Just a sample wget of a 1GB file has an eta over 3 hours

![image](https://user-images.githubusercontent.com/259316/73114830-2b6d2a80-3eec-11ea-981f-caf25b4077eb.png)

Switching to `RequestStrategyFastest`:

![image](https://user-images.githubusercontent.com/259316/73114847-5e172300-3eec-11ea-9e25-85a7b717ba3f.png)

And my internet connection is currently around 50 Mbps.

**Comment by anacrolix** [comment]
That's interesting, but this issue is resolved then. I'll put the exposed strategies into the next release.
